### ISSUE TITLE
No works in 1.31.0

### ISSUE THREAD

**Issue by vVvlife** [HvyIndustries/crane#391]
Linux Os:  Ubuntu 18.04.1 LTS
VSCode Version : 1.31.0
Crane Version : 0.3.8

no any suggestions LOL

**Comment by ezzyfezzy** [comment]
Same here. On Win10. 

Re-index  and other crane commands shows "command 'crane.rebuildSources' not found" error.

`Error: command 'crane.rebuildSources' not found
    at Proxy.t._tryExecuteCommand (commandService.ts:59)
    at commandService.ts:52
    at process._tickCallback (internal/process/next_tick.js:68)`

**Comment by nevadascout** [comment]
I don't have access to Windows to test this at the moment, but I'll check it in a few days.

**Comment by samirdjelal** [comment]
Same problem, here, latest VSCode version 1.31.1
it seems VSCode switched to Node version 10.2.0
I tried to switch back to the previous version to find out that it works fine. but it doesn't work in the latest version.
**ERROR**
`Activating extension 'HvyIndustries.crane' failed: Cannot find module 'internal/util/types'.`
